Repository MYM-Tech/cornellius-ui, pull requests merged in 2022-08, with the labels that each got.

#19 Fix: Input time jsx
  src/components/Inputs/CorInputTime/CorInputTime.stories.tsx
  src/components/Inputs/CorInputTime/CorInputTime.tsx
  src/components/Inputs/CorInputTime/InputTime.tsx
Labels: bug

#20 Build: Fixing order CI
  .github/workflows/chromatic-publish.yml
  .github/workflows/release.yml
  .github/workflows/storybook-gitpage.yml
  .github/workflows/test-build.yml
Labels: bug, draft

#23 Fix: Fix error release chromatic (COR-NA)
  .github/workflows/release.yml
  package.json
Labels: bug

#25 Fix: Fixing package.json file
  package.json
Labels: bug

#26 Fix: fix input checkbox onChange
  src/components/Inputs/CorInputCheckbox/CorInputCheckbox.stories.tsx
  src/components/Inputs/CorInputCheckbox/CorInputCheckbox.tsx
  src/components/Inputs/CorInputCheckbox/CorInputCheckbox.types.ts
Labels: bug

#27 Fix: Remove onInput abstraction in InputText
  src/components/Inputs/CorInputMoney/CorInputMoney.types.ts
  src/components/Inputs/CorInputText/CorInputText.tsx
  src/components/Inputs/CorInputText/CorInputText.types.ts
  src/components/Inputs/Input.types.ts
Labels: bug

#28 feat: Add InputText variant prop
  src/components/Inputs/CorInputMoney/CorInputMoney.types.ts
  src/components/Inputs/CorInputText/CorInputText.stories.mdx
  src/components/Inputs/CorInputText/CorInputText.stories.tsx
  src/components/Inputs/CorInputText/CorInputText.tsx
  src/components/Inputs/CorInputText/CorInputText.types.ts
Labels: enhancement

#29 Fix: Rename class props in InputProps
  src/components/Inputs/CorInputText/CorInputText.types.ts
  src/components/Inputs/Input.types.ts
Labels: bug

#17 Feat: Input switch
  src/App/index.ts
  src/components/Card/Card.stories.tsx
  src/components/CorButton/CorButton.stories.tsx
  src/components/HelloWorld.tsx
  src/components/Inputs/CorInputCheckbox/CorInputCheckbox.stories.tsx
  src/components/Inputs/CorInputMoney/CorInputMoney.stories.tsx
  src/components/Inputs/CorInputNumber/CorInputNumber.stories.tsx
  src/components/Inputs/CorInputRadio/CorInputRadio.stories.tsx
  src/components/Inputs/CorInputSwitch/CorInpurSwitch.module.scss
  src/components/Inputs/CorInputSwitch/CorInputSwitch.stories.mdx
  src/components/Inputs/CorInputSwitch/CorInputSwitch.stories.tsx
  src/components/Inputs/CorInputSwitch/CorInputSwitch.tsx
  src/components/Inputs/CorTextarea/CorTextarea.stories.tsx
  src/components/LayoutSystem/Content/Content.stories.tsx
  src/components/LayoutSystem/MainLayout/MainLayout.stories.tsx
  src/components/LayoutSystem/MainLayout/MainLayout.tsx
  src/components/LayoutSystem/Sidebar/Sidebar.stories.tsx
  src/components/Modal/CorModal/Modal.stories.tsx
  src/components/Page.tsx
  src/index.tsx
  src/main.ts
Labels: enhancement

#31 Fix: use a if instead of optional chaining
  src/components/Inputs/CorInputCheckbox/CorInputCheckbox.tsx
Labels: bug

#32 Fix: add classname in inputs
  src/components/Inputs/CorInputText/CorInputText.tsx
  src/components/Inputs/CorInputText/CorInputText.types.ts
  src/components/Inputs/CorTextarea/CorTextarea.tsx
  src/components/Inputs/CorTextarea/CorTextarea.types.ts
  src/components/Inputs/Input.types.ts
Labels: bug
